export type Service = {
  slug: string;
  name: string;
  shortIntro: string;
  summary: string;
  goals: string[];
  homeSuitability: string;
  difficulties: string[];
  sessionIncludes: string[];
  benefitsFor: string[];
  faqs: { question: string; answer: string }[];
  relatedSlugs: string[];
  metaDescription: string;
  featured?: boolean;
};

export const services: Service[] = [
  {
    slug: "cervical-spondylosis-physiotherapy",
    name: "Cervical Spondylosis Physiotherapy",
    shortIntro: "Support for neck stiffness, postural strain, and daily discomfort linked with cervical wear and tear.",
    summary: "Home physiotherapy for cervical spondylosis can focus on easing movement difficulty, reducing neck strain, and improving posture during daily routines.",
    goals: ["Improve neck mobility", "Reduce stiffness", "Build postural support"],
    homeSuitability: "Well suited for home sessions because assessment and exercise can be tailored to the patient's usual setup.",
    difficulties: ["Neck stiffness after rest", "Pain while looking down", "Headache linked to posture"],
    sessionIncludes: ["Movement assessment", "Gentle mobility work", "Posture guidance", "Home exercise progression"],
    benefitsFor: ["Desk-based workers", "Older adults", "People with recurring neck tightness"],
    faqs: [
      { question: "Can home physiotherapy help with posture habits?", answer: "Yes. Sessions may include practical posture and workstation advice alongside exercises." },
      { question: "Will treatment be forceful?", answer: "Treatment is adjusted to symptoms and tolerance, with a careful, gradual approach." },
    ],
    relatedSlugs: ["neck-pain-physiotherapy", "spine-mobilisation", "cervical-lumbar-spondylitis-physiotherapy"],
    metaDescription: "Home physiotherapy for cervical spondylosis in Gaur City 2 and Greater Noida with posture support, mobility work, and personalised exercises.",
    featured: true,
  },
  {
    slug: "cervical-lumbar-spondylitis-physiotherapy",
    name: "Cervical and Lumbar Spondylitis Physiotherapy",
    shortIntro: "Home care support for combined neck and lower-back pain patterns.",
    summary: "When both the neck and lower back are affected, physiotherapy planning needs to balance pain relief, safer movement patterns, and practical exercise pacing.",
    goals: ["Support daily movement", "Improve spinal control", "Reduce repeated strain"],
    homeSuitability: "Home visits allow the therapist to adapt mobility and strengthening work around the routines the patient actually uses.",
    difficulties: ["Neck and back pain together", "Difficulty sitting or standing long", "Reduced flexibility"],
    sessionIncludes: ["Spinal movement review", "Core and postural exercises", "Transfer advice", "Activity pacing guidance"],
    benefitsFor: ["Adults with sedentary routines", "People recovering from flare-ups", "Patients needing one-to-one movement coaching"],
    faqs: [
      { question: "Do both areas get assessed together?", answer: "Yes. Neck and lumbar symptoms often influence each other, so home assessment reviews both." },
      { question: "Can exercises be simple to follow?", answer: "Yes. Home programmes are usually kept clear, practical, and realistic." },
    ],
    relatedSlugs: ["cervical-spondylosis-physiotherapy", "slipped-disc-pivd-physiotherapy", "spine-mobilisation"],
    metaDescription: "Book home physiotherapy for cervical and lumbar spondylitis in Greater Noida with personalised spinal mobility and exercise support.",
    featured: true,
  },
  {
    slug: "slipped-disc-pivd-physiotherapy",
    name: "PIVD / Slipped Disc Physiotherapy",
    shortIntro: "Guided home physiotherapy for movement difficulty, back pain, and nerve-related symptoms.",
    summary: "For PIVD or slipped disc concerns, home physiotherapy can help patients move with better confidence, manage aggravating positions, and build recovery habits safely.",
    goals: ["Support safer movement", "Reduce pain-provoking habits", "Progress return to activity"],
    homeSuitability: "Home sessions are helpful when travel is uncomfortable or symptoms worsen during prolonged sitting or transfers.",
    difficulties: ["Pain on bending", "Pain radiating to the leg", "Trouble changing position"],
    sessionIncludes: ["Movement screening", "Directional exercises when suitable", "Positioning advice", "Functional movement retraining"],
    benefitsFor: ["Adults with back-related leg pain", "People uncomfortable travelling", "Patients needing pacing guidance"],
    faqs: [
      { question: "Is rest always the answer?", answer: "Not always. The plan often balances symptom relief with gradual movement and activity guidance." },
      { question: "When should urgent medical help be considered?", answer: "Sudden bladder or bowel loss, severe weakness, or major trauma needs urgent medical care." },
    ],
    relatedSlugs: ["sciatica-physiotherapy", "spine-mobilisation", "orthopaedic-physiotherapy"],
    metaDescription: "Home slipped disc and PIVD physiotherapy in Gaur City 2 with exercise guidance, movement training, and practical home recovery support.",
    featured: true,
  },
  {
    slug: "orthopaedic-physiotherapy",
    name: "Orthopaedic Physiotherapy",
    shortIntro: "Home physiotherapy for joint pain, stiffness, movement limitations, and rehabilitation support.",
    summary: "Orthopaedic physiotherapy at home can support patients dealing with muscle, bone, joint, or post-injury movement challenges across many age groups.",
    goals: ["Improve movement confidence", "Build strength and control", "Support functional recovery"],
    homeSuitability: "Home sessions work well when exercise, walking practice, and day-to-day movement training are easier to coach in the patient's actual environment.",
    difficulties: ["Joint stiffness", "Pain with walking", "Reduced balance or strength"],
    sessionIncludes: ["Functional assessment", "Strength work", "Mobility drills", "Exercise progression plan"],
    benefitsFor: ["Adults after injury", "Elderly patients", "People recovering from orthopaedic setbacks"],
    faqs: [
      { question: "Is orthopaedic physiotherapy only for surgery recovery?", answer: "No. It may also support pain management, mobility work, and non-surgical rehabilitation." },
      { question: "Can family members be guided too?", answer: "Yes, where useful, caregivers can be shown how to support safe movement practice." },
    ],
    relatedSlugs: ["knee-pain-physiotherapy", "arthritis-rehabilitation", "sports-injury-rehabilitation"],
    metaDescription: "Orthopaedic home physiotherapy in Greater Noida for pain, mobility, rehabilitation, and movement recovery in daily life.",
    featured: true,
  },
  {
    slug: "knee-pain-physiotherapy",
    name: "Knee Pain Physiotherapy",
    shortIntro: "Support for knee pain that affects stairs, walking, standing, or confidence with movement.",
    summary: "Home physiotherapy for knee pain can focus on strength, flexibility, confidence during walking, and reducing strain during everyday activities.",
    goals: ["Improve walking comfort", "Build knee support strength", "Ease stair and chair transfers"],
    homeSuitability: "Home treatment is useful because real-life triggers like stairs, seating height, and walking surfaces can be addressed directly.",
    difficulties: ["Pain with stairs", "Reduced knee bend", "Difficulty rising from a chair"],
    sessionIncludes: ["Gait observation", "Strength drills", "Range of motion work", "Load-management advice"],
    benefitsFor: ["Older adults", "Patients with arthritic knee pain", "People recovering from minor injury"],
    faqs: [
      { question: "Can treatment be started without special equipment?", answer: "Yes. Many early exercises can be done using chairs, walls, and simple household support." },
      { question: "Will every knee pain case need the same plan?", answer: "No. The exercises and pace depend on the cause, irritation level, and goals." },
    ],
    relatedSlugs: ["arthritis-rehabilitation", "acl-rehabilitation", "orthopaedic-physiotherapy"],
    metaDescription: "Knee pain physiotherapy at home in Gaur City 2 with strength, walking support, mobility work, and practical home exercise planning.",
    featured: true,
  },
  {
    slug: "neck-pain-physiotherapy",
    name: "Neck Pain Physiotherapy",
    shortIntro: "A focused home-based plan for everyday neck pain, stiffness, and reduced movement tolerance.",
    summary: "Home physiotherapy for neck pain can support mobility, postural control, and day-to-day comfort without relying on generic routines.",
    goals: ["Improve neck movement", "Reduce postural overload", "Support daily comfort"],
    homeSuitability: "Home care is helpful when symptoms relate to sleeping position, work posture, or daily screen use that can be reviewed on site.",
    difficulties: ["Pain turning the head", "Morning stiffness", "Tension linked to screen work"],
    sessionIncludes: ["Pain pattern review", "Mobility exercises", "Posture coaching", "Self-management advice"],
    benefitsFor: ["Professionals", "Students", "Older adults with stiffness"],
    faqs: [
      { question: "Can pillow habits be discussed?", answer: "Yes. Sleep positioning and routine habits can be part of the home review." },
      { question: "Do you provide only exercise sheets?", answer: "The plan usually includes hands-on guidance, movement correction, and follow-up progression." },
    ],
    relatedSlugs: ["cervical-spondylosis-physiotherapy", "spine-mobilisation", "therapeutic-taping"],
    metaDescription: "Home neck pain physiotherapy in Greater Noida with posture advice, mobility work, and personalised home exercise support.",
    featured: true,
  },
  {
    slug: "sciatica-physiotherapy",
    name: "Sciatica Physiotherapy",
    shortIntro: "Home physiotherapy support for leg symptoms linked with lower-back irritation or nerve sensitivity.",
    summary: "Sciatica physiotherapy at home can focus on easing painful movement patterns, improving confidence with walking, and guiding safe activity progression.",
    goals: ["Support walking tolerance", "Reduce nerve irritation triggers", "Improve day-to-day function"],
    homeSuitability: "Useful when sitting, travelling, or prolonged standing worsens symptoms and the patient needs practical home-based advice.",
    difficulties: ["Pain running down the leg", "Pins and needles", "Discomfort during sitting or getting up"],
    sessionIncludes: ["Symptom behaviour review", "Movement strategy coaching", "Neural mobility when appropriate", "Home recovery planning"],
    benefitsFor: ["Adults with back-related leg symptoms", "Patients preferring home care", "People needing function-based coaching"],
    faqs: [
      { question: "Can home physiotherapy replace medical evaluation?", answer: "Physiotherapy supports management, but new severe symptoms may still need medical review." },
      { question: "Is movement always avoided?", answer: "Usually not. Safe, well-chosen movement often plays an important role." },
    ],
    relatedSlugs: ["slipped-disc-pivd-physiotherapy", "spine-mobilisation", "orthopaedic-physiotherapy"],
    metaDescription: "Sciatica physiotherapy at home in Greater Noida with practical movement support, exercise advice, and symptom-aware rehabilitation.",
    featured: true,
  },
  {
    slug: "stroke-rehabilitation",
    name: "Stroke Physiotherapy Rehabilitation",
    shortIntro: "Home rehabilitation support aimed at mobility, transfers, balance, and daily function after stroke.",
    summary: "Stroke rehabilitation at home may help patients and families work on movement recovery, confidence, and functional practice in a familiar environment.",
    goals: ["Improve mobility and transfers", "Support balance and safety", "Encourage functional repetition"],
    homeSuitability: "Home sessions are especially valuable after stroke because movement retraining can happen where the patient actually lives and functions.",
    difficulties: ["Weakness on one side", "Balance issues", "Difficulty getting out of bed or walking safely"],
    sessionIncludes: ["Functional assessment", "Bed and chair transfer practice", "Balance work", "Caregiver guidance"],
    benefitsFor: ["Patients after hospital discharge", "Families needing structured support", "People with mobility limitations"],
    faqs: [
      { question: "Can a family member stay during the session?", answer: "Yes. Caregiver involvement is often helpful during stroke rehabilitation." },
      { question: "Will recovery be the same for every patient?", answer: "No. Progress varies and plans are adjusted according to the patient's condition and goals." },
    ],
    relatedSlugs: ["neurophysiotherapy", "orthopaedic-physiotherapy", "knee-pain-physiotherapy"],
    metaDescription: "Home stroke physiotherapy rehabilitation in Gaur City 2 with mobility practice, balance support, and caregiver guidance.",
    featured: true,
  },
  {
    slug: "neurophysiotherapy",
    name: "Neurophysiotherapy",
    shortIntro: "Home physiotherapy support for neurological movement challenges and rehabilitation goals.",
    summary: "Neurophysiotherapy can support patients living with neurological conditions through movement practice, positioning advice, balance work, and caregiver education.",
    goals: ["Support functional movement", "Improve safety and balance", "Encourage consistent home practice"],
    homeSuitability: "Home visits help because therapy can be adapted to the patient's actual surroundings, transfers, and mobility aids.",
    difficulties: ["Poor balance", "Weakness or tone changes", "Difficulty with transfers"],
    sessionIncludes: ["Mobility assessment", "Balance retraining", "Transfer practice", "Home setup advice"],
    benefitsFor: ["Neurological rehabilitation patients", "Elderly patients", "Families supporting home care"],
    faqs: [
      { question: "Can sessions be tailored to fatigue levels?", answer: "Yes. Pacing is important and the plan can be adjusted to the patient's tolerance." },
      { question: "Do home sessions include caregiver instruction?", answer: "When relevant, yes. Safe support techniques can be reviewed with the family." },
    ],
    relatedSlugs: ["stroke-rehabilitation", "orthopaedic-physiotherapy", "sciatica-physiotherapy"],
    metaDescription: "Home neurophysiotherapy in Greater Noida with balance work, transfer support, and practical rehabilitation at home.",
    featured: true,
  },
  {
    slug: "sports-injury-rehabilitation",
    name: "Sports Injury Rehabilitation",
    shortIntro: "Home-based rehabilitation for return to movement after sports-related strain or injury.",
    summary: "Sports injury rehabilitation can focus on pain-aware loading, mobility, strength rebuilding, and safe return to activity with a realistic progression plan.",
    goals: ["Restore movement quality", "Build strength gradually", "Support return to activity"],
    homeSuitability: "Home sessions work well during the early and middle stages of rehab when exercise quality and confidence matter most.",
    difficulties: ["Loss of strength", "Pain during activity", "Fear of re-injury"],
    sessionIncludes: ["Movement review", "Strength progression", "Load management", "Home exercise programming"],
    benefitsFor: ["Active adults", "Amateur athletes", "Patients after sports-related setbacks"],
    faqs: [
      { question: "Can home rehab still be structured for sports goals?", answer: "Yes. Programmes can be staged clearly even without clinic equipment." },
      { question: "Is complete rest the only approach?", answer: "Usually no. The plan often uses progressive loading at an appropriate level." },
    ],
    relatedSlugs: ["acl-rehabilitation", "tennis-elbow-physiotherapy", "therapeutic-taping"],
    metaDescription: "Home sports injury rehabilitation in Greater Noida with progressive exercise, mobility work, and return-to-activity support.",
    featured: true,
  },
  {
    slug: "acl-rehabilitation",
    name: "ACL Rehabilitation",
    shortIntro: "Home rehabilitation support for knee control, strength, and return-to-activity milestones.",
    summary: "ACL rehabilitation at home can focus on movement quality, strength progression, and confidence as recovery advances.",
    goals: ["Restore knee control", "Build strength and confidence", "Support staged functional recovery"],
    homeSuitability: "Home visits are useful for early and ongoing rehab when gait, stairs, and daily loading need close observation.",
    difficulties: ["Instability feelings", "Weak quadriceps", "Reduced confidence on stairs"],
    sessionIncludes: ["Gait review", "Strength work", "Range of motion support", "Functional progression planning"],
    benefitsFor: ["Post-injury patients", "Post-operative patients when home care is preferred", "Active adults"],
    faqs: [
      { question: "Can rehab continue after the first few weeks?", answer: "Yes. ACL rehab usually progresses across multiple phases." },
      { question: "Do exercises change over time?", answer: "They should. Progression is based on function, tolerance, and stage of recovery." },
    ],
    relatedSlugs: ["knee-pain-physiotherapy", "sports-injury-rehabilitation", "orthopaedic-physiotherapy"],
    metaDescription: "ACL rehabilitation at home in Gaur City 2 with knee strengthening, movement support, and stage-wise exercise progression.",
    featured: true,
  },
  {
    slug: "arthritis-rehabilitation",
    name: "Arthritis Rehabilitation",
    shortIntro: "Gentle, practical home physiotherapy to support movement and confidence with arthritis-related pain or stiffness.",
    summary: "Arthritis rehabilitation can focus on protecting joint function, improving tolerance for daily activity, and building manageable exercise habits at home.",
    goals: ["Maintain joint movement", "Support strength and function", "Reduce stiffness during the day"],
    homeSuitability: "Home visits make it easier to adapt exercises, transfers, and activity pacing to the patient's daily environment.",
    difficulties: ["Morning stiffness", "Joint discomfort with activity", "Reduced walking confidence"],
    sessionIncludes: ["Activity review", "Joint-friendly exercise planning", "Mobility routines", "Pacing guidance"],
    benefitsFor: ["Older adults", "People with mobility difficulty", "Patients wanting one-to-one support at home"],
    faqs: [
      { question: "Can exercise still be useful during arthritis?", answer: "Yes. Well-chosen exercise can support mobility, strength, and function." },
      { question: "Will the programme be too strenuous?", answer: "The plan should match the patient's symptoms, tolerance, and goals." },
    ],
    relatedSlugs: ["knee-pain-physiotherapy", "orthopaedic-physiotherapy", "neurophysiotherapy"],
    metaDescription: "Home arthritis rehabilitation in Greater Noida with gentle movement guidance, strengthening, and day-to-day function support.",
    featured: true,
  },
  {
    slug: "tennis-elbow-physiotherapy",
    name: "Tennis Elbow Physiotherapy",
    shortIntro: "Home treatment support for elbow pain affecting grip, lifting, and repetitive daily tasks.",
    summary: "Tennis elbow physiotherapy can help patients manage load, improve forearm strength, and modify repetitive tasks that keep symptoms active.",
    goals: ["Reduce strain during hand use", "Improve forearm strength", "Support comfortable daily function"],
    homeSuitability: "Home care works well because symptom-provoking tasks and hand-use habits can be reviewed directly.",
    difficulties: ["Pain on gripping", "Pain while lifting objects", "Difficulty with repetitive hand work"],
    sessionIncludes: ["Load review", "Forearm strengthening", "Activity modification advice", "Progress tracking"],
    benefitsFor: ["Working adults", "Homemakers", "People with repetitive-use strain"],
    faqs: [
      { question: "Do I need sports activity to have tennis elbow?", answer: "No. It can affect anyone doing repetitive gripping or hand-intensive tasks." },
      { question: "Can home tools be used during rehab?", answer: "Yes. Household items can often help with exercise progression." },
    ],
    relatedSlugs: ["orthopaedic-physiotherapy", "therapeutic-taping", "sports-injury-rehabilitation"],
    metaDescription: "Tennis elbow physiotherapy at home in Greater Noida for grip-related pain, forearm strength, and practical activity modification.",
    featured: true,
  },
  {
    slug: "spine-mobilisation",
    name: "Spine Mobilisation",
    shortIntro: "Movement-focused support to help the spine move more comfortably and efficiently.",
    summary: "Spine mobilisation as part of a broader physiotherapy plan can support mobility, posture, and symptom-aware exercise progression for spinal discomfort.",
    goals: ["Improve spinal motion", "Ease stiffness", "Support better movement patterns"],
    homeSuitability: "Home sessions allow mobilisation work to be combined with practical movement coaching and daily habit correction.",
    difficulties: ["General spinal stiffness", "Pain during turning or bending", "Postural tightness"],
    sessionIncludes: ["Movement assessment", "Mobilisation techniques when suitable", "Follow-up exercises", "Posture advice"],
    benefitsFor: ["Adults with stiffness", "People with sedentary routines", "Patients needing guided mobility work"],
    faqs: [
      { question: "Is mobilisation the only part of recovery?", answer: "Usually not. It often works best alongside exercise and movement retraining." },
      { question: "Will the plan still include home practice?", answer: "Yes. Home exercises and habit changes help maintain progress." },
    ],
    relatedSlugs: ["neck-pain-physiotherapy", "cervical-spondylosis-physiotherapy", "sciatica-physiotherapy"],
    metaDescription: "Home spine mobilisation in Gaur City 2 with personalised movement guidance, posture support, and follow-up exercises.",
    featured: true,
  },
  {
    slug: "therapeutic-taping",
    name: "Therapeutic Taping",
    shortIntro: "Supportive taping strategies that may be used alongside exercises and movement guidance.",
    summary: "Therapeutic taping may be added to a home physiotherapy plan to support comfort, cue movement, or assist function depending on the condition and assessment.",
    goals: ["Support movement confidence", "Assist symptom management", "Complement exercise and rehab work"],
    homeSuitability: "Suitable as an add-on during home sessions when the therapist identifies a clear reason to use taping as part of the wider plan.",
    difficulties: ["Joint support needs", "Movement awareness issues", "Exercise carryover between sessions"],
    sessionIncludes: ["Skin and suitability check", "Condition-specific taping when appropriate", "Usage guidance", "Exercise integration"],
    benefitsFor: ["Sports rehab patients", "Joint pain patients", "People needing short-term movement support"],
    faqs: [
      { question: "Does taping replace exercise?", answer: "No. It is usually one part of a broader physiotherapy plan." },
      { question: "Why is this called therapeutic taping?", answer: "The source phrase appeared non-standard, so the service has been named using a clearer medical term." },
    ],
    relatedSlugs: ["sports-injury-rehabilitation", "neck-pain-physiotherapy", "tennis-elbow-physiotherapy"],
    metaDescription: "Therapeutic taping during home physiotherapy in Greater Noida as part of a personalised rehabilitation and movement-support plan.",
    featured: true,
  },
];

export const additionalServices = [
  "Adult Rehabilitation",
  "Rheumatoid Arthritis Physiotherapy",
  "Electrical Stimulation",
  "Sports Massage Therapy",
  "Knee Care",
  "Sprain Rehabilitation",
  "Sports Fracture Rehabilitation",
];

export function getService(slug: string) {
  return services.find((service) => service.slug === slug);
}
